name: Build

on:
    push:
        branches:
        - main

env:
    APP_NAME: tmgw-wifi-authorizer

jobs:
    build-for-linux:
        name: Build for Linux
        runs-on: ubuntu-latest

        env:
            TARGET: x86_64-unknown-linux-gnu

        steps:
        - uses: actions/checkout@v3
        - run: cargo build --release --target $TARGET
        - uses: actions/upload-artifact@v3
          with:
            name: $TARGET
            path: target/$TARGET/release/$APP_NAME

    build-for-windows:
        name: Build for Windows
        runs-on: windows-latest

        env:
            TARGET: x86_64-pc-windows-msvc

        steps:
        - uses: actions/checkout@v3
        - run: cargo build --release --target $env:TARGET
        - uses: actions/upload-artifact@v3
          with:
            name: $TARGET
            path: target/$TARGET/release/$APP_NAME.exe

    build-for-macos:
        name: Build for macOS
        runs-on: macos-latest

        env:
            TARGET: x86_64-apple-darwin

        steps:
        - uses: actions/checkout@v3
        - run: cargo build --release --target $TARGET
        - uses: actions/upload-artifact@v3
          with:
            name: $TARGET
            path: target/$TARGET/release/$APP_NAME